export const questions = [
  {
    question: 'Loved ones describe my personality as:',
    options: [
      {
        optionText: 'Sophisticated',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Mature',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Youthful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Serious',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Cute',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Friendly',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Confident',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Graceful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Wise',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'Loved ones describe my appearance as:',
    options: [
      {
        optionText: 'Sophisticated',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Mature',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Youthful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Serious',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Cute',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Friendly',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Confident',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Graceful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Feminine',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Wise',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
];
