export const questions = [
  {
    question: 'Loved ones describe my personality as:',
    options: [
      {
        optionText: 'Bougie',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Responsible',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Child-like',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Leader-like',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Cute',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Friendly',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Confident',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Graceful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Introspective',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Reserved or shy',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Charming and/or flirty',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Chaotic and/or unhinged',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Spicy',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Well-mannered',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Calm',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'People think that I:',
    options: [
      {
        optionText: 'Appear/act younger than my age',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Appear/act my actual age',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Appear/act more mature than my age',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'Friends and loved ones describe my appearance as:',
    options: [
      {
        optionText: 'Sophisticated',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Mature',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Youthful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Serious',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Sweet and/or innocent',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Warm and approachable',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Confident',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Graceful',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Feminine',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Wise',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Clean and put together',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Intimidating',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'My eyebrows appear:',
    options: [
      {
        optionText: 'Sharply defined and/or angular',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Straight',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Full and/or dark',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Pointed and/or peaked',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Gently arched',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Not overly heavy, but not too thin',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Delicate',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Thin',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'My eyes appear:',
    options: [
      {
        optionText: 'Angled',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Deep set',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Close set',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Average sized for my face',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Large for my face',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Rounded',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Upturned',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Downturned',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Wide set',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Heavy lidded',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'My nose appears:',
    options: [
      {
        optionText: 'Straight',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Long',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Pointed',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Convex',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Strong shaped',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Wide',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Short',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Upturned',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Average sized',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Delicate',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Small',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Flat',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Low nose bridge',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'I have the following face shape:',
    options: [
      {
        optionText: 'Oval',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Round',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Heart-shaped face',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Square or rectangular',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Trigular',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'My facial structure is/has:',
    options: [
      {
        optionText: 'Long',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Pronounced cheekbones',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Angular',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Small',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Apple cheeked',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Small and/or pointed chin',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Rounded cheeks or chin',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Wide forehead',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Soft cheekbones',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Symmetrical',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'My mouth can be described as:',
    options: [
      {
        optionText: 'Wide',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Thin lips',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Full/Heavy lips',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Curved Shape',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Average sized lips',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Small',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Upturned',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Rounded lips',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'One lip is bigger than the other',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Pale in color',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Defined Cupids Bow',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'My hair/hairstyle can be described as:',
    options: [
      {
        optionText: 'Center/Middle Part',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Slicked Back',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Widows Peak',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Large afro',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Casual and natural',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Medium sized afro',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Waves',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Short',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Dreadlocks',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Spiky',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Curly',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Cornrows',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Shaggy Layers',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Ponytail',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Bangs',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Short Afro',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Simple and neat',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Long',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Side Part',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Braids',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Wispy',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Straight',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Medium length hair',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'People perceive my height as:',
    options: [
      {
        optionText: 'Shorter than my actual height',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'my actual height',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Taller than my actual height',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'I feel most comfortable in:',
    options: [
      {
        optionText: 'Baggy/oversized clothing',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Form-fitting clothing',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Low-cut necklines',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Luxurious fabrics (e.g. silk, satin, etc)',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Soft breathable fabrics',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Timeless styles (rather than trendy)',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Clothes that make a statement',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Comfortable clothing',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Flowy clothing',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Cute, doll-like accessories and clothing',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText:
          'Clothes with intricate and delicate detailing (e.g. beading, lace)',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
      {
        optionText: 'Polished and elevated clothing',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'Choose all that describe your voice:',
    options: [
      {
        optionText: 'Low-pitched',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'Animated',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Subdued',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Well-modulated',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Soft',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 1,
        },
      },
      {
        optionText: 'High-pitched',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Upbeat',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Strong',
        score: {
          dramatic: 1,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Husky',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Clear',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Feminine',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
    ],
  },
  {
    question: 'Pick the expressions that you relate with:',
    options: [
      {
        optionText: 'Danger can be interesting, boredom is death',
        score: {
          dramatic: 1,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Comfort first and foremost',
        score: {
          dramatic: 0,
          natural: 1,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Would go crazy working in a cubicle',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 1,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText:
          'Able to be both a leader of others and to be a fair team player',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 1,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Secretly attracted to naughty people',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 1,
          ethereal: 0,
        },
      },
      {
        optionText: 'Life is a party',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 1,
          romantic: 0,
          ethereal: 0,
        },
      },
      {
        optionText: 'Appears as if from another era – or another world',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 1,
        },
      },
    ],
  },
  {
    question: 'TEMPLATE QUESTION',
    options: [
      {
        optionText: 'TEMPLATE OPTION',
        score: {
          dramatic: 0,
          natural: 0,
          gamine: 0,
          classic: 0,
          ingenue: 0,
          romantic: 0,
          ethereal: 0,
        },
      },
    ],
  },
];
